### PR TITLE
Fix symfony 5 BC deprecation alert on TreeBuilder

### PR DESCRIPTION
**Pull request by florianajir**
fix symfony v5.*  breaking change on TreeBuilder::root()

### CODE REVIEW

**Comment by eschmar** [comment]
@florianajir thanks for the fix, there is now an official version `^2.0.0` supporting symfony 5 and its new twig dependency with namespaces

**Comment by florianajir** [comment]
could this fix be in next sf 4.* compatible release  ?

**Comment by florianajir** [comment]
will this `v2.0.0` still keep sf 4.* support ?

**Comment by eschmar** [comment]
as long as you are using twig >=3..0.0, it should be compatible

**Pull request merged**
